[package]
name = "servo-test"
version = "0.1.0"
authors = ["Oszkar <jozsa.oszkar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pwm-pca9685 = "0.3"
linux-embedded-hal = "0.3"
embedded-hal = "0.2.4"